spring.datasource.url=jdbc:mysql://localhost:3306/movie_booking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG


# JWT config

jwt_secret=supersecretkey1234567890abcdef1234567890abcd
jwt.expiration=86400000

# 86400000 ms = 1 day

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
reset.base-url=http://localhost:8081/#/reset

server.port=8081